# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='_User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
