# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170808_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='_User',
            new_name='User',
        ),
    ]
