# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170820_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Stripe_Created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Stripe_ID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
