# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20170809_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='set',
            name='Code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
