# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Thumbnail',
            field=models.FileField(default=0, upload_to='static/videos/Thumbnails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='File',
            field=models.FileField(upload_to='static/videos/'),
        ),
    ]
