# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_set_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='Level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='Week',
            field=models.IntegerField(default=0),
        ),
    ]
