# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_exercise_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Exercise_Type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
