# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_video_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='Users.Member'),
        ),
    ]
