# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20170809_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='_Date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
