# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20170829_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='Date',
            field=models.DateField(),
        ),
    ]
