# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20170816_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='_User',
        ),
    ]
