# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20170829_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='Block',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Block_Num',
            field=models.IntegerField(default=0),
        ),
    ]
