# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_workout__user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Type', models.CharField(default='', max_length=200)),
                ('Sets', models.IntegerField(default=0)),
                ('Reps', models.IntegerField(default=0)),
                ('Order', models.IntegerField(default=0)),
                ('Workout', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Users.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='Sets',
            field=models.IntegerField(default=0),
        ),
    ]
