# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20170830_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Set_1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Set_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Set_3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Set_4',
            field=models.CharField(default='', max_length=10),
        ),
    ]
