# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20170816_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkout',
            name='Workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='SubWorkouts',
            field=models.ManyToManyField(default='', to='Users.SubWorkout'),
        ),
    ]
