# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20170831_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Video_Description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
