# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_exercise_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
