# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_subworkout_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkout',
            name='Exercise',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise'),
        ),
    ]
