# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20170816_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkout',
            name='Exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise'),
            preserve_default=False,
        ),
    ]
