# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20170816_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(default=0)),
                ('Ordered_ID', models.IntegerField(default=0)),
                ('Week', models.IntegerField(default=0)),
                ('Day', models.IntegerField(default=0)),
                ('_Date', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='subworkout',
            name='RPE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='Ordered_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='SubWorkouts',
            field=models.ManyToManyField(default='', to='Users.SubWorkout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='Template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.Workout_Template'),
            preserve_default=False,
        ),
    ]
