# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20170817_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='Level_Group',
            field=models.IntegerField(default=0),
        ),
    ]
