# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_workout_template_level_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkout',
            name='Exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise'),
        ),
    ]
